### ISSUE TITLE
Multi click on login button calculated as a new sessions 

### ISSUE THREAD

**Issue by Abdalsalaam** [Pierre-Lannoy/wp-sessions#1]
Hi
If user clicked the login button multiple times by mistake, the plugin will calculate every single click as a new session

**Comment by Pierre-Lannoy** [comment]
Hello @Abdalsalaam !
You're right, it's an issue with WordPress login form. Nevertheless, when you don't use Sessions (with session limitation), you can not "see" it. And now with Sessions the issue is a big one...
To be fully honest, I don't know how to do to manage it as Sessions do not "touch" WP login form.

Do you have many user who do that? Did you try to switch the limiter in "override oldest session" ?

**Comment by Abdalsalaam** [comment]
thanks for your reply, yes I have many users doing that, and I didn't tried to  switch the limiter in "override oldest session" because I want to limit the sessions into one session on one device lonely, so I don't want the user to be able to change the device

**Comment by Pierre-Lannoy** [comment]
Hello @Abdalsalaam !

I spent part of my Saturday trying to figure out how this is done, under what conditions and how WordPress implements its login form... The only way to modify this behavior is to do it via JS on the login form. And it will not cover the users who have no JS support nor if you have plugin which alter the login form (like SSO plugins). Do you think it is acceptable?

**Comment by Abdalsalaam** [comment]
@Pierre-Lannoy Thanks for you time 🥇 
I already tried to solve it with JS, my solution : just hide the login button after first click..

but actually its not work on the mac or safari users I don't know why to this moment ( js code work perfectly,  button disabled )

**Comment by Pierre-Lannoy** [comment]
OK. I will try to do something in the next release (will be 2.0.0).
I keep you informed as soon as it is available... (less than 4 weeks if all go well)

**Comment by Abdalsalaam** [comment]
Good luck and many thanks @Pierre-Lannoy
